captainVersion: 4
services:
    $$cap_appname-appsmith:
        image: index.docker.io/appsmith/appsmith-ce:$$cap_appsmith_version
        volumes:
            - $$cap_appname-stacks-data:/appsmith-stacks
        restart: always
        environment:
            APPSMITH_MAIL_ENABLED: $$cap_app_smtp_email_enable
            APPSMITH_DISABLE_TELEMETRY: $$cap_disable_telementry
            APPSMITH_DISABLE_INTERCOM: $$cap_disable_intercom
            APPSMITH_MAIL_FROM: $$cap_app_mailfrom_email
            APPSMITH_REPLY_TO: $$cap_app_replyto_email
            APPSMITH_MAIL_HOST: $$cap_APPSMITH_SMTP_HOST
            APPSMITH_MAIL_PORT: $$cap_APPSMITH_SMTP_PORT
            # ***** Set to true if providing a TLS port ******
            APPSMITH_MAIL_SMTP_TLS_ENABLED: $$cap_app_smtp_tls_enable
            APPSMITH_MAIL_USERNAME: $$cap_APPSMITH_SMTP_USER
            APPSMITH_MAIL_PASSWORD: $$cap_APPSMITH_SMTP_PASSWORD
            APPSMITH_MAIL_SMTP_AUTH: $$cap_app_smtp_auth_enable
            APPSMITH_ADMIN_EMAILS: $$cap_app_admin_email
            # ******** Form Login/Signup ********
            APPSMITH_FORM_LOGIN_DISABLED: $$cap_app_form_login disabled
            APPSMITH_SIGNUP_DISABLED: $$cap_app_signup disabled

caproverOneClickApp:
    variables:
        - id: $$cap_appsmith_version
          label: Appsmith Version
          defaultValue: v1.8.10
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/appsmith/appsmith-ce/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_APPSMITH_SMTP_HOST
          label: APPSMITH | SMTP Server Hostname
          description: Hostname of the SMTP server.
          validRegex: /.{1,}/
        - id: $$cap_APPSMITH_SMTP_PORT
          label: APPSMITH | SMTP Server Port
          description: Port of the SMTP server.
          defaultValue: 587
          validRegex: /.{1,}/
        - id: $$cap_APPSMITH_SMTP_USER
          label: APPSMITH | SMTP User
          description: Username for the SMTP server.
          validRegex: /.{1,}/
        - id: $$cap_APPSMITH_SMTP_PASSWORD
          label: APPSMITH | SMTP Password
          description: Password for the SMTP server.
          validRegex: /.{1,}/
        - id: $$cap_app_mailfrom_email
          label: Appsmith MAILFROM email
          defaultValue: mailfrom@example.com
          validRegex: /[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/
        - id: $$cap_app_replyto_email
          label: Appsmith REPLYTO email
          defaultValue: reply@example.com
          validRegex: /[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/
        - id: $$cap_app_smtp_email_enable
          label: smtp email enable | true or false
          defaultValue: false
          validRegex: /(.*\W|^)(true|false)(\W.*|$)/
        - id: $$cap_app_smtp_auth_enable
          label: smtp email auth | true or false
          defaultValue: true
          validRegex: /(.*\W|^)(true|false)(\W.*|$)/
        - id: $$cap_disable_telementry
          label: telementry disable | true or false
          defaultValue: true
          validRegex: /(.*\W|^)(true|false)(\W.*|$)/
        - id: $$cap_disable_intercom
          label: intercom disable | true or false
          defaultValue: true
          validRegex: /(.*\W|^)(true|false)(\W.*|$)/
        - id: $$cap_app_smtp_tls_enable
          label: smtp email tls | true or false
          defaultValue: true
          validRegex: /(.*\W|^)(true|false)(\W.*|$)/
        - id: $$cap_app_form_login disabled
          label: appsmith form login disabled | true or false
          defaultValue: false
          validRegex: /(.*\W|^)(true|false)(\W.*|$)/
        - id: $$cap_app_signup disabled
          label: appsmith signup disabled | true or false
          defaultValue: false
          validRegex: /(.*\W|^)(true|false)(\W.*|$)/
        - id: $$cap_app_admin_email
          label: Appsmith admin email
          defaultValue: mailfrom@example.com
          validRegex: /[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/

    instructions:
        start: >-
            Appsmith is the fastest way to build internal apps over any database or API.
        end: >-
            Please wait for 2 minutes. Appsmith is deployed and available as $$cap_appname-appsmith. 
            To further enhance the installation, see the complete environment variables here https://github.com/appsmithorg/appsmith/blob/release/deploy/template/docker.env.sh
    displayName: Appsmith.V2
    isOfficial: true
    description: Appsmith is the fastest way to build internal apps over any database or API.
    documentation: Taken from https://docs.appsmith.com/setup/docker
