captainVersion: 4
services:
    $$cap_appname-linkding:
        caproverExtra:
            containerHttpPort: $$cap_linkding_PORT
        image: sissbruecker/linkding:$$cap_linkding_version
        volumes:
            - $$cap_appname-data:/etc/linkding/data
        restart: always
        environment:
            LD_CONTEXT_PATH: $$cap_linkding_con_path
            LD_SUPERUSER_NAME: $$cap_linkding_super_name
            LD_SUPERUSER_PASSWORD: $$cap_linkding_super_pass
            LD_DISABLE_BACKGROUND_TASKS: $$cap_linkding_disable_bg_tasks
            LD_DISABLE_URL_VALIDATION: $$cap_linkding_disable_url_val
            LD_ENABLE_AUTH_PROXY: $$cap_linkding_enable_auth_proxy
            LD_AUTH_PROXY_USERNAME_HEADER: $$cap_linkding_proxy_header
            LD_AUTH_PROXY_LOGOUT_URL: $$cap_linkding_proxy_logout
            LD_CSRF_TRUSTED_ORIGINS: $$cap_linkding_csrf_trusted

caproverOneClickApp:
    variables:
        - id: $$cap_linkding_version
          label: Linkding Version
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/sissbruecker/linkding/tags
          defaultValue: latest
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_linkding_con_path
          label: Context Path | /
          description: e.g linkding/ Must end with a slash `/
          defaultValue:
        - id: $$cap_linkding_super_name
          label: Linkding SuperUser Name
          description: Username of the initial superuser, leave empty to not create one
          defaultValue: superadmin
          validRegex: /^[a-zA-Z0-9]+$/
        - id: $$cap_linkding_super_pass
          label: Linkding SuperUser Pass
          description: Password for the initial superuser
          defaultValue: $$cap_gen_random_hex(16)
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_linkding_disable_bg_tasks
          label: Linkding Disable Tasks
          description: Disable background tasks
          defaultValue: False
          validRegex: /(.*\W|^)(true|false|True|False)(\W.*|$)/
        - id: $$cap_linkding_disable_url_val
          label: Linkding Disable Url Validation
          description: Disable URL validation for bookmarks completely
          defaultValue: False
          validRegex: /(.*\W|^)(true|false|True|False)(\W.*|$)/
        - id: $$cap_linkding_enable_auth_proxy
          label: Linkding Enable Auth Proxy
          description: Header that the auth proxy passes to the application to identify the user
          defaultValue: False
          validRegex: /(.*\W|^)(true|false|True|False)(\W.*|$)/
        - id: $$cap_linkding_proxy_header
          label: Linkding Proxy Username Header
          description: Header that the auth proxy passes https://github.com/sissbruecker/linkding/blob/master/docs/Options.md
          defaultValue:
        - id: $$cap_linkding_proxy_logout
          label: Linkding Proxy Logout
          description: List of trusted origins from which to accept POST requests https://github.com/sissbruecker/linkding/blob/master/docs/Options.md
          defaultValue:
        - id: $$cap_linkding_csrf_trusted
          label: Linkding CSRF Trusted
          description: See docs/Options.md for more details
          defaultValue:
        - id: $$cap_linkding_PORT
          label: Linkding | Port
          description: Port for Web.
          defaultValue: 9090
          validRegex: /.{1,}/

    instructions:
        start: >-
            linkding is a simple bookmark service that you can host yourself. 
            It's designed be to be minimal, fast, and easy to set up using Docker.
        end: >-
            Docker compose file https://github.com/sissbruecker/linkding/blob/master/docker-compose.yml
    displayName: Linkding
    isOfficial: true
    description: linkding is a simple bookmark service that you can host yourself.
    documentation: Taken from https://github.com/sissbruecker/linkding#documentation
