captainVersion: 4
services:

    $$cap_appname-misp-mariadb:
        caproverExtra:
            notExposeAsWebApp: 'true'
        image: mariadb:$$cap_misp-mariadb_version
        restart: always
        hostname: srv-captain--$$cap_appname-misp-mariadb
        tmpfs:
          - /tmp
        environment:
            MYSQL_USER: $$cap_misp_db_user
            MYSQL_DATABASE: $$cap_misp_DB
            MYSQL_PASSWORD: $$cap_db_password
            MYSQL_ROOT_PASSWORD: $$cap_misp_dbroot_password
        volumes:
            - $$cap_appname-mariadb-data:/var/lib/mysql

    $$cap_appname-misp-redis:
        caproverExtra:
            notExposeAsWebApp: 'true'
        image: redis:$$cap_misp_redis_version
        hostname: srv-captain--$$cap_appname-misp-redis
        restart: always

    $$cap_appname-misp-modules:
        caproverExtra:
            notExposeAsWebApp: 'true'
        image: ghcr.io/nukib/misp-modules:$$cap_misp_modules_version
        hostname: srv-captain--$$cap_appname-misp-modules
        restart: always
        cap_drop:
          - NET_RAW
          - SYS_CHROOT
          - MKNOD
          - NET_BIND_SERVICE
          - AUDIT_WRITE
          - SETFCAP

    $$cap_appname-misp:
        caproverExtra:
            containerHttpPort: $$cap_misp_PORT
        image: ghcr.io/nukib/misp:$$cap_misp_version
        hostname: srv-captain--$$cap_appname-misp
        restart: always
        depends_on:
          - $$cap_appname-misp-mariadb
          - $$cap_appname-misp-redis
        tmpfs:
          - /tmp
        cap_drop:
          - NET_RAW
          - SYS_CHROOT
          - MKNOD
          - AUDIT_WRITE
          - SETFCAP
        environment:
            MYSQL_HOST: srv-captain--$$cap_appname-misp-mariadb
            MYSQL_LOGIN: $$cap_misp_db_user
            MYSQL_PASSWORD: $$cap_db_password
            MYSQL_DATABASE: $$cap_misp_DB
            REDIS_HOST: srv-captain--$$cap_appname-misp-redis
            MISP_BASEURL: $$cap_misp_baseurl
            MISP_UUID: $$cap_misp_uuid
            MISP_ORG: $$cap_misp_org
            MISP_MODULE_URL: http://srv-captain--$$cap_appname-misp-modules
            MISP_EMAIL: $$cap_misp_email
            SECURITY_SALT: $$cap_misp_salt
            ZEROMQ_ENABLED: "yes"
        volumes:
            - $$cap_appname-mips-data:/var/www/MISP

    
caproverOneClickApp:
    variables:
        - id: $$cap_misp-mariadb_version
          label: Misp Mariadb Version
          defaultValue: 10.9
          description: Check out their Docker page for the valid tags https://hub.docker.com/_/mariadb/tags
          validRegex: /^([^\s^\/])+$/        
        - id: $$cap_misp_db_user
          label: Misp Database Username
          defaultValue: misp
          validRegex: /^([a-zA-Z0-9_])+$/
        - id: $$cap_db_password
          label: Misp Database Password
          defaultValue: Mispy123
          validRegex: /.{1,}/
        - id: $$cap_misp_DB
          label: Misp Database Name
          description: Name of the database.
          defaultValue: misp
          validRegex: /.{1,}/
        - id: $$cap_misp_dbroot_password
          label: Misp Database Root Password
          defaultValue: Mispy123root
          validRegex: /.{1,}/
        - id: $$cap_misp_redis_version
          label: Misp Redis Version
          defaultValue: 7.0
          description: Check out their Docker page for the valid tags https://hub.docker.com/_/redis/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_misp_modules_version
          label: Misp Modules Version
          defaultValue: latest
          description: Check out their Github page for the valid tags ghcr.io/nukib/misp-modules
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_misp_PORT
          label: ContainerHttpPort | Port
          description: Port for Container. Leave default unless you are sure it needs changing or conflicts with existing.
          defaultValue: 80
          validRegex: /.{1,}/
        - id: $$cap_misp_version
          label: Misp App Version
          defaultValue: latest
          description: Check out their Github page for the valid tags ghcr.io/nukib/misp
          validRegex: /^([^\s^\/])+$/ 
        - id: $$cap_misp_baseurl
          label: Misp Base URL
          description: (required, string) - full URL with https:// or http://
          defaultValue: https://
          validRegex: /.{1,}/
        - id: $$cap_misp_uuid
          label: Misp UUID
          description: (required, string) - MISP instance UUID (can be generated by uuidgen command)
          defaultValue: 6e741108-8986-4f34-8614-dc16ff8d8f4c
          validRegex: /[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[89abAB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}/
        - id: $$cap_misp_org
          label: Misp ORG
          description: (required, string) - MISP default organisation name
          defaultValue: testorg
          validRegex: /.{1,}/
        - id: $$cap_misp_email
          label: Misp Default email
          defaultValue: user@example.com
          validRegex: /[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/
        - id: $$cap_misp_salt
          label: Misp Encrytion Salt
          description: (required, string) - random string (recommended at least 32 chars) used for salting
          defaultValue: $$cap_gen_random_hex(32)
          validRegex: /^(?=.*\d).{10,}$/

    instructions:
        start: |-
            MISP is an open source software solution for collecting, storing, distributing and sharing cyber security indicators and threats about cyber security incidents analysis and malware analysis. MISP is designed by and for incident analysts, security and ICT professionals or malware reversers to support their day-to-day operations to share structured information efficiently.
        end: |-
            MISP container (Docker) image focused on high performance and security based on CentOS Stream 8.
            This image contains the latest version of MISP and the required dependencies. Image is intended as
            immutable, which means that it is not possible to update MISP from the user interface and instead, an admin
            should download a newer image.
            
            Image is based on CentOS Stream 8, so perfectly fits your infrastructure if you use CentOS or RHEL as a host system.
            Modern MISP features are enabled by default (like advanced audit log or storing setting in the database).
            Integrated support for OpenID Connect (OIDC) authentication.
            PHP is by default protected by Snuffleupagus extensions with rules tailored to MISP.
            Optional extensions and configurations that will make MISP faster are enabled.
            Integrated support for logging exceptions to Sentry and forwarding logs to syslog server.
            Final image is automatically tested, so every release should work as expected.
            Build for amd64 (x86_64) and arm64 (aarch64).

            Checkout the full list of ENV variables and additional configurations at their github page https://github.com/NUKIB/misp


    displayName: NUKIB Misp
    isOfficial: false
    description: MISP, Malware Information Sharing Platform and Threat Sharing.
    documentation: Taken from https://github.com/NUKIB/misp/tree/main/docs